name: Trigger repo dispatch action
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  pull_request_review:
    types: [submitted]

jobs:
  codeowners-multiple-owners-check:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger repository dispatch
        uses: myrotvorets/trigger-repository-dispatch-action@1.0.0
        with:
          token: ${{ secrets.REPOSITORY_ACCESS_TOKEN }}
          repo: betasve/learn-gha
          type: codeowners-check
          payload: '{ "ref": "${{ github.ref }}", "sha": "${{ github.sha }}" }'
